### ISSUE TITLE
Discuss whether to track cost metrics with data (e.g. Callable) rather than in separate algorithm-dependent objects (current QueryStats)

### ISSUE THREAD

**Issue by timbittner** [qubrabench/qubrabench#15]
- What do we want to keep track of?
- Wrap basic Function
- Put the stats into QCallable (num quantum calls, num classical calls, quantum cost, classical cost)
- Extract_from function to get stats from different QCallables

**Comment by anurudhp** [comment]
handled by the new API design. we'll discuss further improvements/additions by creating new issues.
