### ISSUE TITLE
Add configuration selection example

### ISSUE THREAD

**Issue by timbittner** [qubrabench/qubrabench#16]
- [ ] craft/pick a small (textbook) example
- [ ] how do we solve it classically (in python)?
- [ ] which subroutines can be replaced with `search`/`max`?

**Comment by catch22** [comment]
Is this still planned?

**Comment by timbittner** [comment]
Its low priority for now but eventually we should deliver on this.

**Comment by catch22** [comment]
Will this be an example or a separate project?

**Comment by timbittner** [comment]
Let's try making this a separate project/repository instead of an example. Might have to add issues to the qubrabench repo if we have troubles with the example but that will be fine.

**Comment by anurudhp** [comment]
updated the todo list
