### ISSUE TITLE
Verify that failure probability epsilon is used correctly

### ISSUE THREAD

**Issue by timbittner** [qubrabench/qubrabench#52]
Cade et al. propose picking `eps = eps_overall / n` as a heuristic (see 4.3.1 in Cade et al.), we should do the same.

- [x] Adjust calculations in simple hillclimber
- [x] Verify quantum statistics anew (there is a discrepancy with the plots in their paper, but we understand why)
- [x] Check steep hillclimber statistics

**Comment by catch22** [comment]
Regarding the second point, thanks to @anurudhp's investigations we now understand the discrepancy and believe that our implementation is correct, so I am checking off this second item. Will be in touch with Chris and friends to synchronize at some point.
