### ISSUE TITLE
Design data processing in qubrabench

### ISSUE THREAD

**Issue by timbittner** [qubrabench/qubrabench#62]
We should define how we want to include the relevant benchmarks for each example problem.

One could for example provide data read folders that contain prominent SAT instances found in research and industry benchmarks.
This would be instead of generating random instances, which for some problems are insufficient in capturing the complexity of a problem. For instance, the hardest SAT problems for current solvers do not necessarily get harder to solve by increasing the number of literals or clauses.

This will likely be an issue for the high-level users of qubrabench that want to see a quantum speedup factor for their problem instances.

**Comment by catch22** [comment]
I don't currently see this as part of qubrabench core.

**Comment by anurudhp** [comment]
usecase dependent, not part of core.
