### ISSUE TITLE
forward http://qubrabench.github.io/  to the docs page

### ISSUE THREAD

**Issue by anurudhp** [qubrabench/qubrabench#98]
> can we make http://qubrabench.github.io/ forward to http://qubrabench.github.io/qubrabench

Two options:
A. Deploy the docs at http://qubrabench.github.io/
e.g. https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository

B. Redirect the page. 
e.g. https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

**Comment by catch22** [comment]
for now i would just non-permanently forward
